package com.wzy.pdmanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACCOUNT_INFO".
 */
public class AccountInfo {

    private Long id;
    private String Title;
    private Integer ICO;
    private Integer Type;
    private String Account;
    private String Password;
    private String Note;
    private String Favorite;
    private java.util.Date AddDate;

    public AccountInfo() {
    }

    public AccountInfo(Long id) {
        this.id = id;
    }

    public AccountInfo(Long id, String Title, Integer ICO, Integer Type, String Account, String Password, String Note, String Favorite, java.util.Date AddDate) {
        this.id = id;
        this.Title = Title;
        this.ICO = ICO;
        this.Type = Type;
        this.Account = Account;
        this.Password = Password;
        this.Note = Note;
        this.Favorite = Favorite;
        this.AddDate = AddDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Integer getICO() {
        return ICO;
    }

    public void setICO(Integer ICO) {
        this.ICO = ICO;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    public String getAccount() {
        return Account;
    }

    public void setAccount(String Account) {
        this.Account = Account;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    public String getFavorite() {
        return Favorite;
    }

    public void setFavorite(String Favorite) {
        this.Favorite = Favorite;
    }

    public java.util.Date getAddDate() {
        return AddDate;
    }

    public void setAddDate(java.util.Date AddDate) {
        this.AddDate = AddDate;
    }

}
