package com.wzy.pdmanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PW_INFO".
 */
public class PwInfo {

    private Long id;
    private String Password;

    public PwInfo() {
    }

    public PwInfo(Long id) {
        this.id = id;
    }

    public PwInfo(Long id, String Password) {
        this.id = id;
        this.Password = Password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

}
